(assert (cellule (nome Eosinofili) (grado 0)))
(assert (cellule (nome Mastociti) (grado 0)))
(assert (cellule (nome Neutrofili) (grado 1)))
(assert (cellule (nome Batteri) (grado 0)))
(assert (cellule (nome Spore) (grado 0)))
(assert (cellule (nome Macchia) (grado 0)))
